server:
  port: 8080
  servlet:
    context-path: /api/v1/

spring:
  application:
    name: LTUDM-Backend
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

r2:
  endpoint: ${R2_ENDPOINT}
  bucket: ${R2_BUCKET}
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  region: auto

jwt:
  secret: ${JWT_SECRET}